name: Most recent works
on:
  schedule: 
    - cron: '0 12 * * *' # Runs every day, 13h00 UTC
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update the description with the desired posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://thephd.github.io/feed.xml,https://soasis.org/posts/index.xml"
